spring:
  application:
    name: update-service
  config:
    import: "configserver:http://localhost:8888/"
  datasource:
    url: "jdbc:postgresql://localhost:5432/livechat"
    username: "admin"
    password: "admin"
  cloud:
    stream:
      kafka:
        binder:
          autoCreateTopics: false
      bindings:
        chat-created-in-0:
          destination: chat_create
    kafka:
      binder:
        brokers: "localhost:9092"

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true