spring:
  application:
    name: notification-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:6060/realms/livechat
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    function:
      definition: created_chat_notification;message_read_event;user_join_event
    stream:
      kafka:
        binder:
          autoCreateTopics: false
      bindings:
        created_chat_notification-in-0:
          destination: created_chat_notification
        notification_accepted-out-0:
          destination: notification_accepted
        message_read_event-in-0:
          destination: message_read
        user_join_event-in-0:
          destination: user_joins