spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webflux:
          metrics:
            enabled: true
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          globalcors:
            add-to-simple-url-handler-mapping: true
            cors-configurations:
              '[/**]':
                allowedOrigins:
                  - "http://localhost:4200"

                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - PATCH
                  - DELETE
                  - OPTIONS

                allowedHeaders:
                  - "*"
                exposedHeaders:
                  - "X-Correlation-Id"

                allowCredentials: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:6060/realms/livechat
  config:
    import: configserver:http://localhost:8888
  main:
    web-application-type: REACTIVE

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true

