spring:
  application:
    name: chat-service
  config:
    import: configserver:http://localhost:8888
  cloud:
    stream:
      kafka:
        binder:
          autoCreateTopics: false
      bindings:
        chat-created-out-0:
          destination: chat_create
        user-joins-out-0:
          destination: user_joins
    kafka:
      binder:
        brokers: "localhost:9092"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:6060/realms/livechat
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true